FROM pytorch/pytorch:1.13.1-cuda11.6-cudnn8-runtime

ADD requirements.txt /tmp/

RUN apt update \ 
    && apt install -y build-essential ffmpeg libsm6 libxext6 git vim cmake g++ wget \ 
    && pip install --no-cache-dir -r /tmp/requirements.txt
